name: Build Mod
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set Android SDK tools
        run: echo "$ANDROID_HOME/build-tools/34.0.0" >> $GITHUB_PATH

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Setup gradle
        run: |
          chmod +x gradlew

      - name: MultiCrafter unit test
        run: |
          ./gradlew test

      - name: Build MultiCrafter
        run: |
          ./gradlew :main:deploy
          ./gradlew distInjection

      - uses: actions/upload-artifact@v4
        with:
          name: MultiCrafterMod
          path: main/build/tmp/deploy/*.jar
      - uses: actions/upload-artifact@v4
        with:
          name: MultiCrafterLibDist
          path: build/tmp/distInjection/*.zip
